version: 2
jobs:
  build:
    working_directory: ~/ycombinator
    docker:
      - image: elixir:1.5.3
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix credo --strict
      - run: mix test
      - run: mix dialyzer
